### PR TITLE
feat:about page accordion part added pink blob

### PR DESCRIPTION
**Pull request by Jiren1247**
@31Hemlock

### CODE REVIEW

**Comment by Jiren1247** [comment]
feat: about page update completed @31Hemlock

**Comment by Jiren1247** [comment]
fix: changed details in about page @31Hemlock

**Comment by Jiren1247** [comment]
fix: ensure the hashtag matches title in small screens @31Hemlock

**Comment by Jiren1247** [comment]
fix:typo, header font, max-w, cut off images, avoid stretching in 1000px screen size @31Hemlock

**Comment by Jiren1247** [comment]
fix: add href to the current link @31Hemlock

**Review by 31Hemlock — APPROVED** [review]

**Pull request merged**
