### PR TITLE
About page

### PR DESCRIPTION
**Pull request by RuochenRockyWang**
I have created the About web page without the subscription part (will add this part in the future). I also added a content container component but it might not be very useful since we can use tailwind. (will delete this components if it's not useful at all)

### CODE REVIEW

**Review by pgf96 — COMMENTED** [review]
Include a breakpoint for margins on a smaller view. Reducing the amount of blue space should make the content space look less cramped.

**Comment by RuochenRockyWang** [comment]
> I think the mobile view needs a few tweaks to the CSS first the text gets a little cramped in the content containers

I have replace all the css styles with tailwind and added break points for mobile device view, please review the about-page branch again. Thank you so much for your comments~

**Comment by RuochenRockyWang** [comment]
> Include a breakpoint for margins on a smaller view. Reducing the amount of blue space should make the content space look less cramped.

I have replaced all the css styles with tailwind and added break points for mobile device view  please review the about-page branch again. Thank you so much for your comments~

**Review by Isaac-Best — APPROVED** [review]
Looks good

**Pull request merged**
